---
- name: "Template sources list"
  template:
    src: sources.list
    dest: /etc/apt/sources.list
  register: out
- name: "Reload packages"
  apt:
    update_cache: yes
  when: "out.changed"
- name: "Install aptitude"
  apt: package=aptitude state=present
- name: "Upgrade"
  apt:
    upgrade: safe